import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ConvexClientProvider} from '@/components/convex-client-provider';
import {ConvexAuthNextjsServerProvider} from "@convex-dev/auth/nextjs/server";
import "./globals.css";
import {Modals} from "@/components/modals";
import {Toaster} from "@/components/ui/sonner";
import {ReactNode} from "react";
import {JotProvider} from "@/components/jotai-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en">
            <body className={inter.className}>
            <ConvexClientProvider>
                <JotProvider>
                    <Toaster
                        closeButton
                        duration={3000}
                        position='top-right'
                        richColors
                        theme='light'
                    />
                    <Modals/>
                    {children}
                </JotProvider>
            </ConvexClientProvider>
            </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
